###C:\Users\Lenovo\Desktop\shop\cmd\abr_plus\abr_plus.http
# Create Order
POST http://localhost:8081/api/v1/orders
Content-Type: application/json

{
    "title": "Eiffel Tower Tour",
    "description": "Guided tour of the iconic landmark"
}

# Get Order by ID
GET http://localhost:8081/api/v1/orders/1
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

# Update Order by ID
PUT http://localhost:8081/api/v1/orders/1
Content-Type: application/json

{
    "title": "Updated Order",
    "description": "Updated description"
}

# Delete Order by ID
DELETE http://localhost:8081/api/v1/orders/1
Content-Type: application/json
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}